language: node_js
node_js:
  - "8"

services:
  - postgresql

before_install:
  - export TZ=Europe/Helsinki

before_script:
  - psql -c 'create database grappa;' -U postgres
  - psql -c 'create schema grappa_test;' -U postgres grappa

env:
  - DATABASE_URL=postgres://postgres@localhost/grappa CONSOLE_OUTPUT=true TOKEN_SECRET=salainen_token

script: npm run test

cache:
  directories:
    - node_modules

after_success:
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker build -t toska/back-grappa2:staging ."
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker push toska/back-grappa2:staging"
  - "[[ $TRAVIS_TAG =~ (v[1-9].+) ]] && docker build -t toska/back-grappa2:latest ."
  - "[[ $TRAVIS_TAG =~ (v[1-9].+) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_TAG =~ (v[1-9].+) ]] && docker push toska/back-grappa2:latest"
  