// Remember to change id counting to start after mock data in studyfield_seed.js!!

module.exports = [
    { studyfieldId: 1, programmeId: 1, name: 'Software Systems' },
    { studyfieldId: 2, programmeId: 1, name: 'Algorithms, Data Analytics and Machine Learning' },
    { studyfieldId: 3, programmeId: 1, name: 'Networking and Services' },
    { studyfieldId: 4, programmeId: 1, name: 'Algorithmic Bioinformatics' },
    { studyfieldId: 5, programmeId: 2, name: 'No studyfield' },
    { studyfieldId: 6, programmeId: 3, name: 'No studyfield' },
    { studyfieldId: 14, programmeId: 5, name: 'No studyfield' },
    { studyfieldId: 20, programmeId: 7, name: 'No studyfield' },
    { studyfieldId: 21, programmeId: 8, name: 'Ohjelmistotekniikka' },
    { studyfieldId: 22, programmeId: 8, name: 'Älykkäät järjestelmät' },
    { studyfieldId: 23, programmeId: 8, name: 'Algoritmit' },
    { studyfieldId: 24, programmeId: 8, name: 'Informaatiojärjestelmät' },
    { studyfieldId: 25, programmeId: 8, name: 'Hajautetut j. ja tietoliikenne' },
    { studyfieldId: 26, programmeId: 8, name: 'sovellettu' },
    { studyfieldId: 27, programmeId: 8, name: 'Kieliteknologia' },
    { studyfieldId: 28, programmeId: 8, name: 'Opettaja' },
    { studyfieldId: 29, programmeId: 8, name: 'Tietokonematemaatikko' },
    { studyfieldId: 30, programmeId: 8, name: 'Ohjelmistot' },
    { studyfieldId: 31, programmeId: 8, name: 'Yleinen' },
    { studyfieldId: 32, programmeId: 8, name: 'testilinja' },
    { studyfieldId: 33, programmeId: 8, name: 'Bioinformatiikka ja laskennallinen biologia' },
    { studyfieldId: 34, programmeId: 8, name: 'Bioinformatiikan maisteriohjelma' },
    { studyfieldId: 35, programmeId: 8, name: 'CBU-ICT -maisteriohjelma' },
    { studyfieldId: 36, programmeId: 8, name: 'Algoritmit ja koneoppiminen' },
    { studyfieldId: 37, programmeId: 8, name: 'Ohjelmistojärjestelmät' },
    { studyfieldId: 38, programmeId: 8, name: 'Algoritminen bioinformatiikka' },
    { studyfieldId: 39, programmeId: 7, name: 'Analysis', majorId: 1 },
    { studyfieldId: 40, programmeId: 7, name: 'Geometry, algebra and topology', majorId: 1 },
    { studyfieldId: 41, programmeId: 7, name: 'Mathematical logic', majorId: 1 },
    { studyfieldId: 42, programmeId: 7, name: 'Mathematical physics', majorId: 1 },
    { studyfieldId: 43, programmeId: 7, name: 'Applied analysis', majorId: 2 },
    { studyfieldId: 44, programmeId: 7, name: 'Mathematical modelling', majorId: 2 },
    { studyfieldId: 45, programmeId: 7, name: 'Mathematics of imaging', majorId: 2 },
    { studyfieldId: 46, programmeId: 7, name: 'Stochastics', majorId: 2 },
    { studyfieldId: 47, programmeId: 7, name: 'Insurance and financial mathematics', majorId: 2 },
    { studyfieldId: 48, programmeId: 7, name: 'Probability modelling', majorId: 2 },
    { studyfieldId: 51, programmeId: 6, name: 'Analysis', majorId: 1 },
    { studyfieldId: 52, programmeId: 6, name: 'Geometry, algebra and topology', majorId: 1 },
    { studyfieldId: 53, programmeId: 6, name: 'Mathematical physics', majorId: 1 },
    { studyfieldId: 54, programmeId: 6, name: 'Mathematical logic', majorId: 1 },
    { studyfieldId: 55, programmeId: 6, name: 'Biomathematics', majorId: 2 },
    { studyfieldId: 56, programmeId: 6, name: 'Applied analysis', majorId: 2 },
    { studyfieldId: 57, programmeId: 6, name: 'Stochastics', majorId: 2 },
    { studyfieldId: 58, programmeId: 6, name: 'Computer aided mathematics', majorId: 2 },
    { studyfieldId: 59, programmeId: 6, name: 'Insurance and financial mathematics', majorId: 2 },
    { studyfieldId: 60, programmeId: 6, name: 'Statistical machine learning', majorId: 2 },
    { studyfieldId: 66, programmeId: 9, name: 'Algorithmic bioinformatics' },
    { studyfieldId: 67, programmeId: 9, name: 'Applied bioinformatics' },
    { studyfieldId: 68, programmeId: 9, name: 'Biomathematics' },
    { studyfieldId: 69, programmeId: 9, name: 'Biostatistics and bioinformatics' },
    { studyfieldId: 70, programmeId: 9, name: 'Eco-evolutionary informatics' },
    { studyfieldId: 71, programmeId: 9, name: 'Systems biology and medicine' },
    { studyfieldId: 72, programmeId: 10, name: 'No studyfield' },
    { studyfieldId: 73, programmeId: 10, name: 'No studyfield (math)', majorId: 4 },
    { studyfieldId: 74, programmeId: 10, name: 'No studyfield (chem)', majorId: 5 },
    { studyfieldId: 75, programmeId: 10, name: 'No studyfield (phys)', majorId: 6 },
    { studyfieldId: 76, programmeId: 11, name: 'No studyfield', majorId: 8 },
    { studyfieldId: 77, programmeId: 6, name: 'No studyfield', majorId: 9 },
    { studyfieldId: 78, programmeId: 4, name: 'No studyfield', majorId: 10 },
    { studyfieldId: 79, programmeId: 6, name: 'Psychometrics', majorId: 3 },
    { studyfieldId: 61, programmeId: 6, name: 'Time series analysis amd econometry', majorId: 3 },
    { studyfieldId: 62, programmeId: 6, name: 'Biometry and bioinformatics', majorId: 3 },
    { studyfieldId: 63, programmeId: 6, name: 'Social statistics', majorId: 3 },
    { studyfieldId: 64, programmeId: 6, name: 'Statistical machine learning', majorId: 3 },
    { studyfieldId: 65, programmeId: 6, name: 'General statistics', majorId: 3 },
    { studyfieldId: 7, programmeId: 4, name: 'Analytical chemistry', majorId: 11 },
    { studyfieldId: 9, programmeId: 4, name: 'Inorganic chemistry', majorId: 11 },
    { studyfieldId: 10, programmeId: 4, name: 'Organic chemistry', majorId: 11 },
    { studyfieldId: 11, programmeId: 4, name: 'Physical chemistry', majorId: 11 },
    { studyfieldId: 12, programmeId: 4, name: 'Polymer chemistry', majorId: 11 },
    { studyfieldId: 13, programmeId: 4, name: 'Radiochemistry', majorId: 11 },
    { studyfieldId: 49, programmeId: 7, name: 'Statistics', majorId: 3 },
    { studyfieldId: 50, programmeId: 7, name: 'Social statistics', majorId: 7 }
]
