name: Release production

on:
  release:
    types: 
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend to production
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: toska/front-grappa2:latest
          build-args: |
            BASE_PATH=/v2/
            GIT_SHA=${{ github.sha }}

      - name: Build and push backend to production
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: toska/front-grappa2:latest
          build-args: |
            BASE_PATH=/v2/
            GIT_SHA=${{ github.sha }}
