name: Release staging frontend

on:
  push:
    branches: 
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/staging-frontend.yml'


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: grappa-frontend
          tags: staging ${{ github.sha }}
          context: frontend
          containerfiles: |
            frontend/Dockerfile
          build-args: |
            NODE_ENV=staging
            BASE_PATH=/staging/
            GIT_SHA=${{ github.sha }}

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}

  sentry-release:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v2

      - name: Pull image and create a container
        run: docker create --name front-grappa2 toska/front-grappa2:staging

      - name: Copy assets from the container
        run: docker cp front-grappa2:/usr/src/app/build ./build

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_URL: https://sentry.cs.helsinki.fi
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: toska
          SENTRY_PROJECT: grappa
        with:
          environment: staging
          set_commits: 'skip'
          sourcemaps: './build/static/js'
          url_prefix: '~/staging/static/js'
