name: Release staging frontend

on:
  push:
    branches: 
      - trunk
    paths:
      - 'frontend/**'
      - '.github/workflows/staging-frontend.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push staging
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: toska/front-grappa2:staging
          build-args: |
            NODE_ENV=staging
            BASE_PATH=/staging/
            GIT_SHA=${{ github.sha }}

  sentry-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Pull image and create a container
        run: docker create --name front-grappa2 toska/front-grappa2:staging

      - name: Copy assets from the container
        run: docker cp front-grappa2:/usr/src/app/build ./build

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_URL: https://sentry.cs.helsinki.fi
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: toska
          SENTRY_PROJECT: grappa
        with:
          environment: staging
          sourcemaps: './build/static/js'
          url_prefix: '~/staging/static/js'
