name: Release staging backend

on:
  push:
    branches: 
      - trunk
    paths:
      - 'backend/**'
      - '.github/workflows/staging-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push staging
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: toska/back-grappa2:staging
          build-args: |
            GIT_SHA=${{ github.sha }}
  sentry-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_URL: https://sentry.cs.helsinki.fi
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: toska
          SENTRY_PROJECT: grappa
        with:
          environment: staging
          set_commits: 'skip'
